// Shared builder for the prerendered events-feed endpoints. Both routes are
// static files regenerated by the nightly build; the on-disk JSON stays full
// for plan-day + other server consumers.
//
// Served-copy trims: past events (with a 1-day grace so paging back doesn't
// hit an empty day) and the server-only `audienceAge` field. The optional
// windowDays cap is how the "near" feed stays small — clients that only show
// the next week or two shouldn't pay for December's events on first paint.
import upcomingData from "../../data/south-bay/upcoming-events.json";

const all = upcomingData as { generatedAt?: string; events?: Record<string, unknown>[] };

function ptDate(offsetDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toLocaleDateString("en-CA", { timeZone: "America/Los_Angeles" });
}

export function buildEventsPayload(windowDays?: number): {
  generatedAt?: string;
  eventCount: number;
  window?: { days: number; through: string };
  events: Record<string, unknown>[];
} {
  const cutoff = ptDate(-1);
  const horizon = windowDays ? ptDate(windowDays) : null;

  const events = (all.events ?? [])
    .filter((e) => {
      const date = e?.date;
      if (typeof date !== "string") return true;
      const day = date.slice(0, 10);
      if (day < cutoff) return false;
      if (horizon && day > horizon) return false;
      return true;
    })
    .map((e) => {
      const trimmed = { ...e };
      delete trimmed.audienceAge;
      return trimmed;
    });

  return {
    generatedAt: all.generatedAt,
    eventCount: events.length,
    ...(windowDays && horizon ? { window: { days: windowDays, through: horizon } } : {}),
    events,
  };
}

export const FEED_CACHE_HEADERS = {
  "Content-Type": "application/json",
  "Cache-Control": "public, max-age=300, s-maxage=300, stale-while-revalidate=86400",
};
